#!/bin/sh

set -o errexit
set -o nounset

readonly version="6.2.0"
readonly remote_target="https://github.com/fmtlib/fmt.git"
readonly local_dir="third_party/fmt/${version}"


if [ "$(basename "$(pwd)")" != 'itch' ]; then
    printf "ERROR: must run from top-level of repository\n" >/dev/stderr
    exit 1
fi

mkdir --parents "${local_dir}"
git clone --depth=1 --branch="${version}" "${remote_target}" build-fmt
cp --recursive build-fmt/include "${local_dir}"
rm --recursive --force build-fmt
